export enum RoleUser {
  Dashboard,
  Account,
  OrdersList,
  OrdersDetail,
  Warranty,
  Profile,
  ProductsList,
  ProductsListInternal,
  ProductsView,
  ProductsViewEuropa,
  ProductsViewEuclid,
  ProductsViewMagic,
  ProductsViewBlue,
  ShippingAddress,
  Home,
  ListBasketClient,
  Payments
}
