this.products = [
  {
    "code": "", "name": "Blue Light",
    "priceBase": 6000, "price1": 5500, "price2": 5600, "price3": 5700,
    "father": "Blue Light",
    "category": "Blue Light",
    "subCategory": "Blue Light",
    "material": "Silicone Hydrogel, Filcon V3 75%",
    "descriptionShort": "My description short by euclid",
    "description": "Designed to combat the eyestrain generated by using digital devices for prolonged periods of time. The Spectrum Blue Light, has proven to alleviate some of these harsh effects from our day to day use of: Tablets, TV’s, Phones, and Computer Screen.",
    "replacementPeriod": "Monthly",
    "warranty": "90",
    "url": "http://spctinternational.com/spectrum-blue-light/",
    "stock": 10,
    "types": [
      {
        "name": "",
        "parameters": [
          { "name": "Base Curve (mm)", "type": "selected", "values": ["8.00", "8.30", "8.60", "8.90", "9.20", "9.50"], "selected": null },
          { "name": "Diameter (mm)", "type": "selected", "values": ["14.0", "14.5", "15.0"], "selected": null },
          { "name": "Sphere (D)", "type": "input", "values": [], "placeholder": "e.g. 15.00", "selected": null }
        ],
        "eyeLeft": null,
        "eyeRight": null
      }
    ],
    "infoAditional": [
      {
        "name": "Properties", "values": [
          { "title": "Toric", "image": "assets/images/products/magiclook/1TONE-1.png", "value":"GRAY" },
          { "title": "Multifocal", "image": "assets/images/products/magiclook/1TONE-1.png", "value":"GRAY" },
          { "title": "3-Monthly", "image": "assets/images/products/magiclook/1TONE-1.png", "value":"GRAY" },
          { "title": "Sylicone Hydrogel", "image": "assets/images/products/magiclook/1TONE-1.png", "value":"GRAY" },
          { "title": "UV Filter", "image": "assets/images/products/magiclook/1TONE-1.png", "value":"GRAY" }
        ]
      }
    ]
  }
];
