this.products = [
  {
    "code": "", "name": "Blue Light",
    "priceBase": 6000, "price1": 5500, "price2": 5600, "price3": 5700,
    "father": "Blue Light",
    "category": "Blue Light",
    "subCategory": "Blue Light",
    "material": "Silicone Hydrogel, Filcon V3 75%",
    "descriptionShort": "My description short by euclid",
    "description": "Designed to combat the eyestrain generated by using digital devices for prolonged periods of time. The Spectrum Blue Light, has proven to alleviate some of these harsh effects from our day to day use of: Tablets, TV’s, Phones, and Computer Screen.",
    "replacementPeriod": "Monthly",
    "warranty": "90",
    "url": "http://spctinternational.com/wp-content/uploads/2017/11/SAPHIR.pdf",
    "stock": 10,
    "types": [
      {
        "name": "",
        "parameters": [
          { "name": "Base Curve (mm)", "type": "selected", "values": ["8.00", "8.30", "8.60", "8.90", "9.20", "9.50"], "selected": null },
          { "name": "Diameter (mm)", "type": "selected", "values": ["14.0", "14.5", "15.0"], "selected": null },
          { "name": "Sphere (D)", "type": "input", "values": [], "placeholder": "e.g. 15.00", "selected": null }
        ],
        "eyeLeft": null,
        "eyeRight": null
      }
    ],
    "infoAditional": [
      {
        "name": "Characteristics", "values": [
          { "title": "More Custom", "description": "Individually made for each eye in all designs" },
          { "title": "More Comfort", "description": "High water content Silicone Hydrogel (75%) with low modulus (MPa 0.13) and non-ionic surface." },
          { "title": "Vision Type", "description": "HD—all day clarity and precision." }

        ]
      },
      {
        "name": "Technical Specifications", "values": [
          { "title": "Material", "description": "Silicone Hydrogel, Filcon V3 75%" },
          { "title": "DK", "description": "60" },
          { "title": "MPa", "description": "0.29" },
          { "title": "Handling Tint", "description": "No" },
          { "title": "UV Blocking", "description": "No" },
          { "title": "Base Curve (mm)", "description": "6.80 to 9.80 Steps 0.30" },
          { "title": "ØT (mm)", "description": "13.00 to 16.00 Steps 0.50" },
          { "title": "Sphere (D)", "description": "-30.00 to +30.00 Steps 0.25" },
          { "title": "Cylinder (D)", "description": "-0.75 to -8.00 Steps 0.25" },
          { "title": "Axis (°)", "description": "All Steps 1°" },
          { "title": "Addition (D)", "description": "+0.50 to +4.00 Steps 0.50" },
          { "title": "Desing MF", "description": "CD – CN" }

        ]
      }
    ]
  }
];
